### ISSUE TITLE
[Plugin] Unclear gradle-plugin attribute settings for Bintray

### ISSUE THREAD

**Issue by tlinkowski** [kordamp/kordamp-gradle-plugins#164]
The following code adds a `gradle-plugin` attribute for Bintray:
https://github.com/aalmiray/kordamp-gradle-plugins/blob/d2b636a55fff4c4aece45d634849c9a99764b877/plugins/plugin-gradle-plugin/src/main/groovy/org/kordamp/gradle/plugin/plugin/PluginPlugin.groovy#L114-L117

However, this is set per *entire project*, so I'm wondering if this works as intended.

For example, for the latest version of Kordamp ([0.25.0 on Bintray](https://bintray.com/aalmiray/kordamp/kordamp-gradle-plugins/0.25.0)), the value of this attribute is:
```
org.kordamp.gradle.build-scan:org.kordamp.gradle:buildscan-gradle-plugin
```

PS. I noticed this because I want to upload my Gradle plugin publications to Bintray without applying Kordamp's Plugin plugin (https://github.com/tlinkowski/tlinkowski-superpom/issues/45), and I'm wondering whether I need this `gradle-plugin` attribute or not.

**Comment by aalmiray** [comment]
I think this might be a side effect of publishing all Kordamp plugins under the same package.

**Comment by tlinkowski** [comment]
Hm, and they shouldn't be published like that? I also published like that because I saw you do it 😃

Actually, on my first attempt to include [tlinkowski-superpom](https://bintray.com/tlinkowski/maven/tlinkowski-superpom) package in JCenter, JFrog Support raised concerns about putting two logical packages under one. However, I referred them to [kordamp-gradle-plugins](https://bintray.com/aalmiray/kordamp/kordamp-gradle-plugins), and they responded just with:

> Your request to include your package /tlinkowski/maven/tlinkowski-superpom in Bintray's JCenter has been approved.

Anyway, I wonder how this `gradle-plugin` attribute might be useful... I also [have this attribute set](https://bintray.com/tlinkowski/maven/tlinkowski-superpom/0.1.1) to the first plugin now (`pl.tlinkowski.gradle.my.settings:pl.tlinkowski.gradle.my:my-settings-gradle-plugin`).

**Comment by aalmiray** [comment]
It's a convenience to put all "modules" under a single package, as you can sync with Maven Central with the click of a button instead of many. In the past I configured a package per project (like this https://bintray.com/griffon/griffon) and the Bintray plugin did not allow automatic syncing with MC. It was a tedious task to sync every package manually.

**Comment by tlinkowski** [comment]
I see, thanks for the insight.

However, even though Bintray plugin does support automatic MC sync now, it still "feels" somewhat better to have all the modules of a *single project* in a single place (being a Bintray package). This seems to correspond to how they share versions and other metadata.

**Comment by aalmiray** [comment]
I believe the `gradle-plugin` attribute is no longer needed if the standard Gradle plugin publication mechanism is used. Removing the use of this attribute in `org.kordamp.gradle.plugin`.
