### ISSUE TITLE
Improper usage of @DelegatesTo

### ISSUE THREAD

**Issue by musketyr** [kordamp/kordamp-gradle-plugins#238]
It probably has a no bigger impact on the usage unless you're using static compilation but the usage of `@DelegatesTo` across the project is missing `strategy = Closure.DELEGATE_FIRST`. it might also help to provide better content assist.

**Comment by aalmiray** [comment]
Gradle will eventually execute the closure using this code

    private static <T> void configureTarget(Closure configureClosure, T target, ConfigureDelegate closureDelegate) {
        if (!(configureClosure instanceof GeneratedClosure)) {
            new ClosureBackedAction<T>(configureClosure, Closure.DELEGATE_FIRST, false).execute(target);
            return;
        }

        // Hackery to make closure execution faster, by short-circuiting the expensive property and method lookup on Closure
        Closure withNewOwner = configureClosure.rehydrate(target, closureDelegate, configureClosure.getThisObject());
        new ClosureBackedAction<T>(withNewOwner, Closure.OWNER_ONLY, false).execute(target);
    }

**Comment by musketyr** [comment]
either way, I believe the closure should act pretty the same as when the strategy is set to `DELEGATE_FIRST`.

see e.g https://medium.com/@musketyr/groovy-dsl-builders-3-the-aid-df2e9a02557a
