### ISSUE TITLE
ability to publish POM project

### ISSUE THREAD

**Issue by musketyr** [kordamp/kordamp-gradle-plugins#253]
if you have a POM subproject using `java-platform` plugin then the subproject is not published to BinTray

example https://github.com/agorapulse/micronaut-libraries/tree/master/subprojects/micronaut-aws-sdk-dependencies

**Comment by aalmiray** [comment]
Perhaps a temporary workaround would be to use the òrg.kordamp.gradle.bom`plugin instead http://kordamp.org/kordamp-gradle-plugins/#_org_kordamp_gradle_bom

**Comment by aalmiray** [comment]
Looks like `org.kordamp.gradle.publishing` must be aware of https://docs.gradle.org/current/userguide/java_platform_plugin.html#sec:java_platform_publishing

**Comment by musketyr** [comment]
Thanks!
