### ISSUE TITLE
Task with name 'aggregateJacocoReport' not found in root project ''.

### ISSUE THREAD

**Issue by smac89** [kordamp/kordamp-gradle-plugins#254]
I'm getting this error with the latest version of the project (0.31.2).

It happens when I apply the plugin `'org.kordamp.gradle.java-project'`, and still occurs even after I add the following to the root project and all subprojects:

```
beforeEvaluate {
    config {
        coverage {
            jacoco {
                enabled = false
            }
            coveralls {
                enabled = false
            }
        }
    }
}
```

Here is a stacktrace:

```
Caused by: org.gradle.api.UnknownTaskException: Task with name 'aggregateJacocoReport' not found in root project 'littlecity'.
	at org.gradle.api.internal.tasks.DefaultTaskCollection.createNotFoundException(DefaultTaskCollection.java:102)
	at org.gradle.api.internal.tasks.DefaultTaskCollection.createNotFoundException(DefaultTaskCollection.java:46)
	at org.gradle.api.internal.DefaultNamedDomainObjectCollection.named(DefaultNamedDomainObjectCollection.java:359)
	at org.gradle.api.internal.tasks.DefaultTaskCollection.named(DefaultTaskCollection.java:112)
	at org.kordamp.gradle.plugin.coveralls.CoverallsPlugin$2.execute(CoverallsPlugin.groovy:85)
	at org.kordamp.gradle.plugin.coveralls.CoverallsPlugin$2.execute(CoverallsPlugin.groovy)
	at org.kordamp.gradle.plugin.coveralls.CoverallsPlugin$_configureRootProject_closure1.doCall(CoverallsPlugin.groovy:79)
```

**Comment by aalmiray** [comment]
There's no need to use the `beforeEvaluate` block.
Did you apply the ` org.kordamp.gradle.coveralls` plugin before ` org.kordamp.gradle.java-project`?

**Comment by smac89** [comment]
No I did not apply the `coveralls` plugin, only the `java-project` plugin.

**Comment by aalmiray** [comment]
I'm afraid I can't replicate this problem. Could you tell me more about your setup? What are the contents of `settings.gradle` and how are all plugins applied for example.

**Comment by smac89** [comment]
Here is an example:
https://github.com/MVCE-Superstars/KordmapPluginMVCE

**Comment by aalmiray** [comment]
Thanks. I see what's happening now. The `org.kordamp.gradle.java-project` plugin must be applied to the root project. A `config` block must be added to the root, containing default configuration that all children projects inherit.

Here's the minimum configuration required to get the MVCE to work

    plugins {
        id 'base'
        id 'org.kordamp.gradle.java-project' version '0.31.2'
    }
    
    group 'org.example'
    version '1.0-SNAPSHOT'
    
    allprojects {
        repositories {
            jcenter()
            mavenCentral()
        }
    }
    
    config {
        info {
            vendor      = rootProject.name
            description = rootProject.name
            scm {
                url = 'https://github.com/MVCE-Superstars/KordmapPluginMVCE'
            }
            organization {
                url = 'https://github.com/MVCE-Superstars'
            }
        }
    
        licensing { enabled = false }
    }
    
    subprojects {
        apply plugin: 'java'
    
        sourceCompatibility = '11'
    
        config {
            info {
                name        = project.name
                description = project.name
            }
        }
    }
    
    wrapper {
        distributionType = Wrapper.DistributionType.BIN
        gradleVersion = '5.6.4'
    }

**Comment by smac89** [comment]
Thanks for the explanation
