### ISSUE TITLE
Support Gradle 4.10.1

### ISSUE THREAD

**Issue by musketyr** [kordamp/kordamp-gradle-plugins#260]
I just wonder if there is any chance to support a bit older version of Gradle. This is the last version of Gradle which works well with Grails 3.x and it would help a lot with upgrading from Grails 3.x to Grails 3.4.

**Comment by aalmiray** [comment]
This may be tricky, Kordamp is moving to support the Property/Provider API which I think came out in Gradle 5.

**Comment by musketyr** [comment]
ok
