### ISSUE TITLE
[Sonar] - Next steps

### ISSUE THREAD

**Issue by ursjoss** [kordamp/kordamp-gradle-plugins#271]
I'd like to contribute to getting the sonar-plugin ready for merging into master and thereafter into a released version of the kordamp-gradle-plugins - the current state waiting in branch [sonar](https://github.com/kordamp/kordamp-gradle-plugins/tree/sonar).

What are the steps we need to tackle to get this ready for it? What is preventing it from happening? How could I help getting it into gears?

**Comment by aalmiray** [comment]
I was under the impression that the sonar branch was already merged into master, clearly I forgot to merge it.

**Comment by ursjoss** [comment]
Thank you! :-) You might also want to delete the sonar branch now that it's merged...
