### ISSUE TITLE
kordamp.org via HTTPS

### ISSUE THREAD

**Issue by szpak** [kordamp/kordamp-gradle-plugins#283]
I would be useful to have http://kordamp.org available via HTTPS.

As it seems to be hosted via GitHub pages it should be possible (and easy):
https://github.blog/2018-05-01-github-pages-custom-domains-https/

**Comment by aalmiray** [comment]
As it happens the guide is hosted at gh-pages but the `kordamp.org` is redirected form another server that does not have HTTPS enabled. I'll look into that.

**Comment by szpak** [comment]
I see. In that case, maybe it would be easier (than configuring Let's Encrypt on your server) to do not use the root (apex) domain `kordamp.org`, but `www.kordamp.org` (or anything else) to make it easier to point the A record for only that subdomain in DNS only to GitHub and have HTTPS server by GH pages?

**Comment by aalmiray** [comment]
Fixed. `www.kordamp.org` is now under HTTPS. `kordamp.org` redirects to `www.kordamp.org`.

**Comment by szpak** [comment]
`kordamp.org` also seems to works perfectly fine with https, thanks!

![image](https://user-images.githubusercontent.com/148013/80309365-e13e6280-87d4-11ea-9a89-c08e493959d4.png)
