### ISSUE TITLE
Project changelog

### ISSUE THREAD

**Issue by szpak** [kordamp/kordamp-gradle-plugins#284]
I wasn't able to find a changelog with functional changes in particular releases (commits can be helpful, but are inefficient to read). Maybe there could be some ascidoctor file (or whatever) with important changes for people considering upgrade?

**Comment by aalmiray** [comment]
I tend to group issues by milestone but yes, a changelog would be a good idea.

**Comment by szpak** [comment]
I missed the milestones. They seem to be sensible managed, so you maybe consider using some tools to generate changelog based on it (I haven't used it, so I cannot recommend any). As a last resort there could be mentioned somewhere in README and changes are kept in milestones.

**Comment by szpak** [comment]
Thanks!

**Comment by aalmiray** [comment]
Now to figure out a way to fix #283 😏
