### ISSUE TITLE
[Publishing] PluginMarker publication should not be enhanced

### ISSUE THREAD

**Issue by aalmiray** [kordamp/kordamp-gradle-plugins#293]

**Comment by mhoffrog** [comment]
@aalmiray What was the actual reason to exclude *PluginMarker from publication POM configuration? If I would like to deploy to MavenCentral, then the POM must be configured for the PluginMarker as well to pass MavenCentral POM policy rules.

**Comment by aalmiray** [comment]
AFAIR Gradle plugins use the gradle-plugin-plugin to publish their metadata. In the past that was a custom artifact repository. Nowadays I think these files go into MC via an alternate route. 

Attempting to publish gradle plugins as if they simply were any other artifact you'd push to MC seems (to me) a path that's painful to follow. 

Better to use the gradle provided mechanism to publish said artifacts.

**Comment by mhoffrog** [comment]
> Attempting to publish gradle plugins as if they simply were any other artifact you'd push to MC seems (to me) a path that's painful to follow.

Publishing Gradle plugins to MC is working straight forward, if the POMs of all artifacts are configured accordingly. So if this plugin would not exclude the Marker from POM configuring and it would configure it like it does for the pluginMaven publication all is working fine.

**Comment by aalmiray** [comment]
Hmm that wasn't the case before and thus why the plugin marker pom was not enhanced. 

Perhaps it's time to review this change once more.
