### ISSUE TITLE
Settings plugin and IDEA

### ISSUE THREAD

**Issue by dmurat** [kordamp/kordamp-gradle-plugins#297]
I applied the settings plugin on a nested project structure. And it works as expected. Unfortunately, IDEA displays a suffix for nested projects with qualified project names. This is very distracting for me (old habits, I guess). So, I'm wondering if there is some way to make IDEA behave in a more unsurprising way.

Here is a screenshot of what I will like to have:

![image](https://user-images.githubusercontent.com/470930/81215187-3cdccd00-8fd9-11ea-956c-df5af1637ef5.png)

After applying the settings plugin I get the following:

![image](https://user-images.githubusercontent.com/470930/81215323-79102d80-8fd9-11ea-917a-8c93530b256e.png)

Tnx

**Comment by dmurat** [comment]
I forget to ask, why not using the native Gradle way of nesting projects with colon syntax (`:subprojects:project1`, etc)?

**Comment by aalmiray** [comment]
Because it's shorter to type `:project1:task` than `:subprojects:project1:task`. It might not seen like much but the paths can get really long if you have a 3rd to nth level project structure. The disadvantage is of course that paths must be unique. There may be cases where conflicts may arise when subpaths are equal but their parent are not. In which case perhaps adding a flag to regain the default behavior would be a good idea.

**Comment by aalmiray** [comment]
Do note that on your first screenshot, `subprojects` is treated as a project. You can verify this by invoking `gradle projects`, also because that folder has bold font in IntelliJ.

**Comment by dmurat** [comment]
Yes, I'm aware of this and did make some adjustments in a build script to work around this. If I can choose, I will still rather use that kind of setup since I rarely execute commands on subprojects directly. Unfortunately, with kordamp I cannot have that kind of layout and those nice kordamp aggregate reports. 

To be fair, after an hour, IDEA's module name rendering bothers me less, but I don't believe that at least some of my coworkers will be easily convinced :-) 

Btw, I'm not quite sure, but it looks like that Gradle renders these module names, and IDEA just displays them.

**Comment by dmurat** [comment]
I found an option in IDEA for configuring qualified names of the module. There are some complicated methods through UI (https://www.jetbrains.com/help/idea/creating-and-managing-modules.html#), but I found it much easier to set `<option name="useQualifiedModuleNames" value="false" />` in `.idea/gradle.xml`. What a relief 😄

**Comment by aalmiray** [comment]
OK, so there's a fix for the module name in IDEA. I've got a fix for the long paths as well.

**Comment by dmurat** [comment]
Now with module names resolved, I kinda like kordamp short version 😃 . It simplifies my build script somewhat, containing directory is not rendered in bold since it is not a real module, and all aggregate reports are working. Great.

**Comment by aalmiray** [comment]
Good. I sill think is a good idea to keep the long paths option albeit disabled by default. Long live short project paths!

**Comment by aalmiray** [comment]
Is there something else that needs to be done for this issue?

**Comment by dmurat** [comment]
No. Tnx for the effort. I will close it now.
