### ISSUE TITLE
In Groovydoc plugin link to Groovy API is hardcoded to version 2.5.6

### ISSUE THREAD

**Issue by dmurat** [kordamp/kordamp-gradle-plugins#301]
I'm using Groovy 3.0.3, so it does not suit me to link to the Groovy 2.5.6.

I believe the problem originates from `org.kordamp.gradle.plugin.base.plugins.Groovydoc` constructor. I'm not quite sure how to handle it. Maybe with some additional configuration option, maybe by adding user-configured entries at the start of the set (if this works) or maybe via some more elaborate resolving mechanism similar to the one used for resolving Java documentation.

I'm using kordamp 0.36.0

Tnx.

**Comment by dmurat** [comment]
Forgot to mention, the documentation states that default is an empty set. It should enumerate actual defaults.

**Comment by aalmiray** [comment]
I think you can override the set by assigning an empty value, then add the link you need

    config {
        docs {
            groovydoc {
                links = [] as Set
                options {
                    link 'http://docs.groovy-lang.org/3.0.3/html/api/', 'groovy.', 'org.codehaus.groovy.', 'org.apache.groovy.'
                }
            }
        }
    }

**Comment by dmurat** [comment]
It does not work for me. If I set links on `groovydoc`, Gradle compilation fails. If I move it under `options` Gradle compilation passes, but links still point to the 2.5.6 version.

**Comment by aalmiray** [comment]
Yes, sorry, setting the `links` property should be in `options`, my mistake. However, default links from the parent will override your settings. I added a fix for overriding links by URL.

Unfortunately there's no option in `0.36.0` that will let you remove the default link to Groovy `2.5.6`.

**Comment by dmurat** [comment]
Thnk you. No problem, I can wait for `0.37.0`.
