### ISSUE TITLE
[Codenarc] Improving flexibility of CodeNarc plugin

### ISSUE THREAD

**Issue by dmurat** [kordamp/kordamp-gradle-plugins#304]
I tried to use the CodeNarc plugin, and I found several limitations with it. It's not that plugin is not working. It works as conceived, I guess, but it does not suit me in its current state. So I'm wondering if it can be improved to add some more flexibility.

First, I will like to use Groovy syntax for rules, instead of XML.

Next, for me, it's rather unusual to have different rules for multiple modules inside one project. Although this might be useful, I usually need just two rule sets, one for `main` source set and another for `test` source set across all modules. I believe such a setup is more common.

I'm not quite sure how this can be implemented. I guess supporting Groovy syntax for CodeNarc rules should not be too hard, but flexible configuration with source set support sounds harder. Maybe this can be supported with some expressions for processing of a path to the rule configuration, say `/config/codeNarc/codenarc-${moduleName}-${sourceSet}.groovy`or something like that. A simpler variant which requires explicit configuration per source set would also be great.

Currently, I achieved my goals with custom `build.gradle` scripting to get aggregate reports for `main` and `test` source sets. I used kordamp CodeNarc plugin's source as a guide and inspiration. 

Tnx

**Comment by dmurat** [comment]
I read the changes (did not run them) and tried to understand them, and I'm uncertain if something like the following is possible now. 

Say I have two explicit configuration files, `support/codenarc/codenarcMain.groovy` and `support/codenarc/codenarcTest.groovy` intended to be applied on all modules for their `main` and `test` source sets. Can this be achieved now?

I realized that I was not clear enough in my initial request. I apologize.

**Comment by aalmiray** [comment]
I see now. No, those two options are missing but I can added them :smile:

**Comment by aalmiray** [comment]
By the way, the file discovery assumes files are placed at the root `config/codenarc`.

**Comment by dmurat** [comment]
Yes, I figure out that part. I was thinking about adding explicit, rather than discovered, configuration files. In that scenario, config files should not be discovered, but source set names still need to be.

**Comment by aalmiray** [comment]
- OK. There must be a naming convention to find out if the set value refers to a fixed file or a filename that should take `sourceSetName` into account. Or does it?

The scenarios I’m thinking are:

1.
root sets configFile = “config/codenarc/foo.groovy”
child sets nothing. 

Is root.configFile fixed when evaluating in child or should sourceSetName be taken into consideration?
Is it reasonable to try foo-${sourceSetName}.groovy before foo.groovy?

2.
root sets configFile = “config/codenarc/foo.groovy”
child sets configFile = “config/codenarc/bar.groovy”

child.configFile is chosen but same question as before, is sourceSetName taken into account here?

**Comment by dmurat** [comment]
I guess anything that child sets should have the highest priority. If a child sets nothing and all config files are given by root only, then I was thinking that matching can go something like this (I'm using non-default root here to emphasize explicit configuration):

`support/codenarc/codenarc${moduleName}${sourceSetName}.groovy`
`support/codenarc/codenarc${sourceSetName}.groovy`
`support/codenarc/codenarc.groovy`

So, with two explicit config files given in root configuration

`support/codenarc/codenarcMain.groovy`
`support/codenarc/codenarcTest.groovy`

the configuration will be applied across all modules for their `main` and `test` source sets respectively. Generated aggregate reports will be `aggregateCodenarcMain` and `aggregateCodenarcTest`. Is something like this feasible?

**Comment by aalmiray** [comment]
Yes, I think it can be arranged. However aggregate reports per sourceSetName might be tricky to get at this stage.

**Comment by dmurat** [comment]
If of any help, you can take a look [here](https://github.com/croz-ltd/klokwrk-project) how I did it with `build.gradle` scripting. Code is mainly taken and adapted from kordamp, so it will be familiar 😄 More importantly, you can see the example of what I will like to achieve.

**Comment by dmurat** [comment]
Better [link](https://github.com/croz-ltd/klokwrk-project/blob/8da057ddf7e0b07ec92f05f6a1dc470d4de9c09c/build.gradle#L53)

**Comment by aalmiray** [comment]
I'm afraid that calculating aggregate reports per sourceSet is a bit more complicated than that. your code snippet works because the root only looks at `main` and `test`, which fine for that setup. But what if you have additional sourceSets, such as `integration-test` or `functional-test`? What if only a subset of modules have these sourceSets and not all?

The logic required at the root for aggregating all these sourceSets must be a bit more elaborate but I think it's doable. What can be done quickly is checking for `config/codenarc/codenatc-${sourceSetName}.[groovy|xml]` which was missing, as well as inspecting a base `configFile` and check if appending `sourceSetName` has a match.

**Comment by dmurat** [comment]
I think that a quick solution is just fine. If possible, I will like to have a configurable path (excluding simple file name) to the base config file.
