### ISSUE TITLE
[Base] Improvement/explanation of projects DSL

### ISSUE THREAD

**Issue by musketyr** [kordamp/kordamp-gradle-plugins#307]
Hi,

I have certain issues when working with the new projects DSL. I'm unable to use the DSL directly but I have to certain tweaks otherwise I get

```
No signature of method: build_405hjq1qkht83376thoef1t9a.projects() is applicable for argument types: (build_405hjq1qkht83376thoef1t9a$_run_closure2) values: [build_405hjq1qkht83376thoef1t9a$_run_closure2@22e81109]
  Possible solutions: inject(groovy.lang.Closure)
```

see https://github.com/musketyr/kordamp-projects-dsl

I need to access the extension as 

```
extensions.getByType(org.kordamp.gradle.plugin.base.ProjectsExtension).with {
```

and wrap the subprojects block with `afterEvaluate`

**Comment by aalmiray** [comment]
I've seen similar errors and must confess that the error message is misleading. The `projects` extension is only added to the rootProject and should be available always when `org.kordamp.gradle.base` is applied to said project.

The error message is actually a syntax error somewhere inside the "configuring" closure of `dir`, `dirs`, `path`, `paths` but it's masked. I'll try to find a way to present a better error message tha hopefully contains the line number and/or the offending syntax error.

**Comment by aalmiray** [comment]
Exceptions due to missing methods should be clearer now https://github.com/kordamp/kordamp-gradle-plugins/commit/5fc7201ccfbc48621430a84e3ed176a63be14b00
Still working on the timing issues related to `afterEvaluate` and reading settings applied to `config`.

**Comment by aalmiray** [comment]
FYI. the linked project requires applying `shadow` to the `services` directory.
Also, there's a missing `:notification-service-blueprint` project.

**Comment by aalmiray** [comment]
@musketyr Do these issues persist with the latest changes found in trunk? I'd like to post a release by the end of the month and I'm hoping I've got this one fixed 😏

**Comment by musketyr** [comment]
@aalmiray with the latest `0.37.0-SNAPSHOT` I can use the `projects` extension directly without any issues. the problem with `afterEvaluate` still persists.

it seems to me that the plugins from `projects` in `settings.gradle` are not applied before the configuration closure is called from `projects` in `build.gradle`.

**Comment by aalmiray** [comment]
@musketyr The Kordamp build makes use of the feature, please see

https://github.com/kordamp/kordamp-gradle-plugins/blob/master/settings.gradle#L39-L58

https://github.com/kordamp/kordamp-gradle-plugins/blob/master/build.gradle#L62-L86

There's no need to have an `afterEvaluate` block for this particular build. Perhaps I missed something. Is it possible to have a look at the build file that are causing you trouble?

**Comment by musketyr** [comment]
I'll try to figure out how to share the build!
