### ISSUE TITLE
[licensing] InvalidUserDataException with missing LICENSE_HEADER despite enabled = false

### ISSUE THREAD

**Issue by ursjoss** [kordamp/kordamp-gradle-plugins#331]
With kordamp-gradle-plugins-0.37.0 (as opposed to 0.36.0 or earlier), I getan `InvalidDataException` 

```
'..../gradle/LICENSE_HEADER' specified for property 'header' does not exist.
```
I don't have the LICENSE_HEADER in the project, but so far it was not required, as the licensing plugin is not enabled:

```
    licensing {
        enabled = false
        licenses {
            license {
                id = "BSD-3-Clause"
            }
        }
    }
```

**Comment by ursjoss** [comment]
I added a reproducer to https://github.com/ursjoss/kordamp-gradle-test-suite

But your solution was quicker :-) Thanks

**Comment by ursjoss** [comment]
I can confirm that both Bugs #331 and #332 are fixed with current state of 0.37.1-SNAPSHOT. Thank you.

**Comment by aalmiray** [comment]
I'll do another round of tests and release 0.37.1 either on Sunday or Monday.

**Comment by ursjoss** [comment]
I'd like to re-open this issue. It was working in 0.37.1 but somehow had a regression in 0.38 and since.

Reproducer can be found [here](https://github.com/ursjoss/kordamp-gradle-test-suite):

```
gradlew -p 04_license_reproducer check
```

Noteworthy: 
- the license configuration is in the root project `04_license_plugin/build.gradle.kts`. There the license plugin is configured but not enabled.
- the effectiveSettings task shows that the license plugin is correctly disabled for the root project `04_license_plugin`, but is in fact enabled for the subproject. Is the assumption wrong that disabling it in the root project should pass the configuration on to the sub-projects?

<details>
<summary>Extract from effectiveSettings task</summary>

```
> Task :effectiveSettings
release: false
 
info:
    name: Kordamp License Reproducer
    description: sample project to validate the license plugin when disabled
 
licensing:
    enabled: false
    licenses:
        APACHE_2_0:
            id: APACHE_2_0
            distribution: repo
            primary: false
 



> Task :project1:effectiveSettings
release: false
 
info:
    name: Kordamp License Reproducer
    description: sample project to validate the license plugin when disabled
 
licensing:
    enabled: true
    licenses:
        APACHE_2_0:
            id: APACHE_2_0
            distribution: repo
            primary: false
```
</details>

**Comment by aalmiray** [comment]
No, your assumption is correct. If no value is set on a child then it’s taken from the root. This is indeed a regression.

**Comment by ursjoss** [comment]
Hi @aalmiray, is there anything I can do to help to resolve this issue?

**Comment by aalmiray** [comment]
Hi @ursjoss, it's taken me longer that I expected to retrofit the codebase with the Property/Provider API. I hope to get it done in September. 

In the meantime, setting explicit `enabled` on each child project should do the trick as workaround. Sorry for the inconvenience.

**Comment by ursjoss** [comment]
No problem. Thanks for mentioning the workaround that can be used for the time being.
