### ISSUE TITLE
Jacoco aggregateTestReport doesn't support `--project-dir`

### ISSUE THREAD

**Issue by Decat-SimonA** [kordamp/kordamp-gradle-plugins#334]
For example you have this project layout:
```
app/build.gradle
app/module1/build.gradle
app/module2/build.gradle
```

if you run `gradle build -p app aggregateJacocoReport aggregateJacocoMerge`, the `jacocoTestReport.xml` will be written in 

```
build/reports/jacoco/aggregate/jacocoTestReport.xml
```
instead of 
```
app/build/reports/jacoco/aggregate/jacocoTestReport.xml
```

**Comment by aalmiray** [comment]
Where's the root project located? Is it inside `app`?

**Comment by aalmiray** [comment]
For a project defined as

    01_java_gradle_groovy/
    ├── build.gradle
    ├── gradle
    │   ├── LICENSE_HEADER
    │   └── wrapper
    │       ├── gradle-wrapper.jar
    │       └── gradle-wrapper.properties
    ├── gradle.properties
    ├── gradlew
    ├── gradlew.bat
    ├── settings.gradle
    └── subprojects
        ├── mine-bom
        │   └── mine-bom.gradle
        ├── project1
        │   ├── project1.gradle
        │   └── src
        │       ...
        ├── project2
        │   ├── project2.gradle
        │   └── src
        │       ...
        ├── project3
        │   ├── project3.gradle
        │   └── src
        │       ...
        └── project4
            └── project4.gradle

Invoking the following commands

  $ pwd
  /tmp/kordamp-gradle-test-suite
  
  $ gradle -p 01_java_gradle_groovy aggregateJacocoReport aggregateJacocoMerge
  ...
  
  $ tree 01_java_gradle_groovy/build/reports/
  01_java_gradle_groovy/build/reports/
  └── jacoco
      └── aggregate
          ├── html
          │   ├── index.html
          │   ├── jacoco-resources
          │   │   ├── branchfc.gif
          │   │   ├── branchnc.gif
          │   │   ├── branchpc.gif
          │   │   ├── bundle.gif
          │   │   ├── class.gif
          │   │   ├── down.gif
          │   │   ├── greenbar.gif
          │   │   ├── group.gif
          │   │   ├── method.gif
          │   │   ├── package.gif
          │   │   ├── prettify.css
          │   │   ├── prettify.js
          │   │   ├── redbar.gif
          │   │   ├── report.css
          │   │   ├── report.gif
          │   │   ├── session.gif
          │   │   ├── sort.gif
          │   │   ├── sort.js
          │   │   ├── source.gif
          │   │   └── up.gif
          │   └── jacoco-sessions.html
          └── jacocoTestReport.xml

The report files are placed at the right place. Did I miss something? Perhaps I'm using a different setup as you.

**Comment by aalmiray** [comment]
It looks like this is working with `0.38.0`. Could you confirm?
