### ISSUE TITLE
How to deal with several subprojects with same name ?

### ISSUE THREAD

**Issue by finalspy** [kordamp/kordamp-gradle-plugins#342]
Suppose I have the following structure (sorry for the messy formatting) : 

├ build.gradle
├ settings.gradle
├ subprojects
│ ├ project1
│   |   └ project1.gradle
 |    └ project2
 **|         └ project2.gradle**
└ othersubprojects
     ├ project2
     **│ └ project2.gradle**
     └ project3
          └ project3.gradle

How am I supposed to deal with such a structure, as a projects scan would result in collision between same name subprojects. 
Currently this get resolved as : 
- project1
**- project2**
- project3

Is there a way to get projects names customized, let's say like <parent>-<project>.
eg. in my case would result in something like : 
- subprojects-project1
- subprojects-project2
- othersubprojects-project2
- othersubprojects-project3

And in a more general way I think a mean for customizing projects names using the parent directory could be useful sometimes to just get the context of the project when names can be confusing. Even if i had only one project2, i have no way to know with a gradle projects command to know that project3 doesn't belong to the same subprojects groups.

**Comment by aalmiray** [comment]
Hmm no, not right now. Kordamp assumes project names to be unique for the time being. It’s possible to configure a name transformation with either prefix or suffix but it’s applied to all projects regardless of their containing directory. 

Changing the name of the project has an impact in the generated JARs and other artifacts. What you ask can certainly be supported by Kordamp at some point but first I’d have to find the implications of such change. 

Curious here, do you publish artifacts for both projects named project2? Do they use different group and/or have a special mapping for the generated JAR?

I’d like to understand the motivation behind having  non unique project names.

**Comment by finalspy** [comment]
Well to be honest right now my concern is more about being able to make a distinction between subprojects of different parent projects, and I didn't encounter the exact same subproject name problem but i guess it'll come soon.
In fact the projects are in the end generating docker images embedding different technologies and we have projects by technologies and subprojects by versions of that specific technology. 
To give a practical example let's say one project is based upon python and another java, I'll have then python and java as project names. Then I'll have subprojects with python version (2.7 3.5 3.6 3.7 3.8) and java version ( 7 8 11 13 14 ).  No collision here but listed pojects will display :  2.7 3.5 3.6 3.7 3.8 7 8 11 13 with no hint on the technology/language. 
Imagine I add R technology with version 3.5 3.6 4.0   and I'm into troubles. 

I have other ways to deal with that by using a subproject name including the parent technology but the loose the magic "convention over configuration" and need to check that parent and subfolders prefixes are matching.  Moreover as the generated artifacts aka docker images relies on the project structure too it results in changing the images names (which I can solve by other means anyway).  

In fact the main concern are the risk of subprojects names collisions, and the readability of projects listing. 

If you just tell me this is not possible right now, I understand and will find another way to do that. 
Anyway I suggest you to detect collisions and at least add a warning in such cases.
(I'm still learning gradle/kotlin so don't know if I'll be able to PR that but I'll have a look into the code anyway )

**Comment by aalmiray** [comment]
I see. The plugin that executes this behavior is `org.kordamp.gradle.settings` which is a convenience plugin to auto-populate the project list. This plugin can be omitted if it causes trouble but of course now you have to use the standard Gradle mechanism to include projects.

The code in question is https://github.com/kordamp/kordamp-gradle-plugins/blob/master/plugins/settings-gradle-plugin/src/main/groovy/org/kordamp/gradle/plugin/settings/internal/ProjectsExtensionImpl.groovy in case you're interested.

I believe global (all projects) and dir/path name transformations may be the way to go. As of `0.38.0` there's a single global name transform for preffix/suffix.

**Comment by aalmiray** [comment]
As stated before, Kordamp expects project names (and paths) to be unique.
Closing.
