### ISSUE TITLE
Publishing plugin does not add Javadoc

### ISSUE THREAD

**Issue by jerzykrlkroche** [kordamp/kordamp-gradle-plugins#358]
Dear all,

I've noticed that the Bintray publishing plugin does not publish the javadoc to Bintray. The plugin versions are 0.39.0.

After some research I figured out, that the javadoc is not visible in the Publishing plugin. 

I can't figure out the actual reason for that - my javadoc file is built in the right place, but does not get picked up by the plugins. Is that something I'm doing wrong?

My all failed attempts are visible here: https://github.com/Roche/spock-geb-quickstart/tree/03-sonatype-javadoc

Please help... :)

**Comment by jerzykrlkroche** [comment]
Quick note - I checked with Gradle 6.5.1 and 6.3.

I also tried to roll back to Kordamp 0.36.0 plugins, but I faced a stacktrace like this:

```
* What went wrong:
Cannot get property 'coverage' on null object

* Try:
Run with --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
java.lang.NullPointerException: Cannot get property 'coverage' on null object
        at org.kordamp.gradle.plugin.coveralls.CoverallsPlugin.configureCoveralls(CoverallsPlugin.groovy:107)
        at org.kordamp.gradle.plugin.coveralls.CoverallsPlugin.access$0(CoverallsPlugin.groovy)
        at org.kordamp.gradle.plugin.coveralls.CoverallsPlugin$1.execute(CoverallsPlugin.groovy:71)
        at org.kordamp.gradle.plugin.coveralls.CoverallsPlugin$1.execute(CoverallsPlugin.groovy)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$3.graphPopulated(DefaultTaskExecutionGraph.java:227)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
(...)
```

**Comment by aalmiray** [comment]
The kordamp/enforcer-gradle-plugin used kordamp `0.39.0` to publish its `0.5.0` version to Bintray. As you can appreciate javadoc, sources, binary, and POM were published successfully

https://github.com/kordamp/enforcer-gradle-plugin/

https://bintray.com/kordamp/maven/enforcer-api/0.5.0#files/org%2Fkordamp%2Fgradle%2Fenforcer-api%2F0.5.0

Are you trying to publish a single or a multi project?

**Comment by jerzykrlkroche** [comment]
Hi Andres,

Thank you for the hint - I will compare the setups and will try to find a way out.

I'm publishing a multi-module project. And, the Bintray plugin is applied to the submodule.

I just noticed that I deleted the branch I was referring to. I've restored the branch. And, here's the link to my build.gradle from that branch:
https://github.com/Roche/spock-geb-quickstart/blob/35ffad0e9cb47b1df505e6aca4f87ea9303b1729/spock-geb-quickstart/build.gradle

Thank you!

**Comment by aalmiray** [comment]
I think I can tell what the problem is: there are no `sources` nor `javadoc` publications, only `main`. Kordamp does not create separate publications for sources and javadoc, rather it attaches artifacts to the `main` publication. Try removing the `publications` value from the `bintray` block.

**Comment by jerzykrlkroche** [comment]
I'm sorry I did not mention that earlier: the sources published just fine. Only javadoc was missing. 

So, eventually, the release package looked like that: 
https://bintray.com/hoffmannlaroche/OpenSource/spock-geb-quickstart/0.1.7#files/com%2Froche%2Fspock%2Fgeb%2Fspock-geb-quickstart%2F0.1.7

I will check your suggestions in the afternoon - thank you so much!

**Comment by jerzykrlkroche** [comment]
Dear Anders,

I think I cleanly reproduced the problem on a separate project:
https://github.com/jerzykrlkroche/kordamp-reproduced

I noted 3 confusing things here:

1. I can't see javadoc artifact:

```
bash-3.2$ ./gradlew publicationSettings

> Task :submodule-a:publicationSettings
main:
    type: Maven
    groupId: com.roche.kordamp.reproduced
    artifactId: submodule-a
    version: 0.1.0-SNAPSHOT
    artifacts:
        artifact 0:
            file: submodule-a/build/libs/submodule-a-0.1.0-SNAPSHOT.jar
            extension: jar
        artifact 1:
            file: submodule-a/build/libs/submodule-a-0.1.0-SNAPSHOT-sources.jar
            classifier: sources
            extension: jar
```

2. I needed to add a dummy `coveralls` task in the submodule: 
  * https://github.com/jerzykrlkroche/kordamp-reproduced/blob/master/submodule-a/build.gradle#L104

Otherwise, I would get this error:

```
bash-3.2$ ./gradlew publicationSettings

FAILURE: Build failed with an exception.

* What went wrong:
Task with name 'coveralls' not found in project ':submodule-a'.
```

3. I needed to add an `aggregateJacocoReport` task in the root project:
  * https://github.com/jerzykrlkroche/kordamp-reproduced/blob/master/build.gradle#L27

Otherwise, I would get this error:

```
bash-3.2$ ./gradlew publicationSettings

FAILURE: Build failed with an exception.

* What went wrong:
Task with name 'aggregateJacocoReport' not found in root project 'root-module'.
```
I think I did everything according to the guide here:
  * http://andresalmiray.com/publishing-artifacts-to-maven-central-with-bintray-gradle/

Unfortunately, Maven Central won't accept artifacts without javadocs, so I need them. 

Is there something I missed?

**Comment by aalmiray** [comment]
I think I know what's happening, specifically with the explicit tasks added to the root: the root project _does_not_ have the Kordamp plugins applied. These plugins are designed in such a way that root configuration can be inherited by child projects.

My recommendation is to apply the `org.kordamp.gradle.java-project` plugin to the root and configure as much as possible there as well, that is, the root's `config` block should contain the configuration shared by all submodules.

Here are some examples

https://github.com/kordamp/kordamp-gradle-plugins/blob/master/build.gradle
https://github.com/kordamp/enforcer-gradle-plugin/blob/master/build.gradle
https://github.com/griffon/griffon/blob/development/build.gradle

**Comment by jerzykrlkroche** [comment]
Hi Anders,

Thank you - your tip fixed all problems at once. And, the submodule now publishes javadoc correctly, too:

```
> Task :submodule-a:publicationSettings
Caching disabled for task ':submodule-a:publicationSettings' because:
  Build cache is disabled
Task ':submodule-a:publicationSettings' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
main:
    type: Maven
    groupId: com.roche.kordamp.reproduced
    artifactId: submodule-a
    version: 0.1.0-SNAPSHOT
    artifacts:
        artifact 0:
            file: submodule-a/build/libs/submodule-a-0.1.0-SNAPSHOT.jar
            extension: jar
        artifact 1:
            file: submodule-a/build/libs/submodule-a-0.1.0-SNAPSHOT-sources.jar
            classifier: sources
            extension: jar
        artifact 2:
            file: submodule-a/build/libs/submodule-a-0.1.0-SNAPSHOT-javadoc.jar
            classifier: javadoc
            extension: jar
```

Thank you so much!
