### ISSUE TITLE
[Sonar] Align properties with Maven plugin

### ISSUE THREAD

**Issue by aalmiray** [kordamp/kordamp-gradle-plugins#406]
`sonar.organization` is required if connecting to "https://sonarcloud.io".
`sonar.login` is required.
`sonar.username` is not needed.

**Comment by ursjoss** [comment]
For what it's worth: The following configuration works for me:

```
        sonar {
            username = "ursjoss"
            configProperties["sonar.organization"] = "ursjoss-github"
        }
```

Of course it will be nicer to defined `sonar.organization` directly in the DSL. Login seems not be necessary though IMHO.

**Comment by aalmiray** [comment]
Strange that `sonar.username` doe snot appear in the following docs

https://docs.sonarqube.org/latest/analysis/scan/sonarscanner-for-gradle/
https://docs.sonarqube.org/latest/analysis/analysis-parameters/
https://sonarcloud.io/documentation/analysis/analysis-parameters/

**Comment by ursjoss** [comment]
Most likely the username would not even be necessary I guess. I'm using a token.

Did you see that the PR breaks the build?

**Comment by aalmiray** [comment]
Yes, sorry about that. Weird that the static type checker in IntelliJ didn't catch it.

**Comment by ursjoss** [comment]
No reason to be sorry. One who dares trying to build from master in a live and kicking project may have to accept an occasional build failure :-)

**Comment by aalmiray** [comment]
Wait, what? You're consuming snapshots built directly from master _and_ I broke your build? O. M. G. So sorry 😢
