### ISSUE TITLE
[licensing] Adding exclusion/inclusion patterns in DSL

### ISSUE THREAD

**Issue by dmurat** [kordamp/kordamp-gradle-plugins#417]
If possible, it would be nice to add support for configuring exclusion patterns directly in config DSL. Otherwise, I have to use a license-gradle-plugin extension to do so. 

I think that exclusion and maybe inclusion patterns are used commonly enough to be included in DSL.

Tnx.

**Comment by dmurat** [comment]
How about adding `META-INF/groovy/*` to the list of exclusions? Together with new exclusions from #423 , I wouldn't have to configure anything 😄 

Tnx.

**Comment by dmurat** [comment]
One more suggestion (with much less justification 😄 ) - excluding all `.gitkeep` files. I believe there is no standard for naming files that are kept in Git repos as placeholders for directories, but I've seen `.gitkeep` used in several places.

**Comment by aalmiray** [comment]
https://github.com/kordamp/kordamp-gradle-plugins/commit/588fdf63df60c0dd066aa3831326cb439a835097
