### ISSUE TITLE
[coveralls] Coveralls stopped working in 0.38.0 and later

### ISSUE THREAD

**Issue by musketyr** [kordamp/kordamp-gradle-plugins#419]
`coveralls` task is never triggered even the env variables `CI` and `COVERALLS_REPO_TOKEN` are present for versions `0.38.0` and later.

example repository https://github.com/agorapulse/micronaut-console

**Comment by musketyr** [comment]
Actually, I might be mistaken. I haven't investigated further but I can publish to Coveralls using `0.31.2`. Version `0.37.0` does trigger the task but does not publish anything. I haven't tried the versions between these two.

**Comment by musketyr** [comment]
Just verified that the last version working gracefully is `0.36.0`.

**Comment by aalmiray** [comment]
Thank you for the investigation. I believe `0.37.0` made changes in the DSL on how properties between child and root projects are evaluated. The problem might be related to that.

**Comment by aalmiray** [comment]
Could you quickly check if enabling `coveralls` explicitly makes it work? `config.coverage.coveralls.enabled = true`.
I think the problem may be relying on `config.coverage.jacoco.enabled` by default.

**Comment by musketyr** [comment]
it made it working - see https://github.com/agorapulse/micronaut-console/pull/3

**Comment by aalmiray** [comment]
I also have a build producing coverage reports but I don't require explicit enabling. However I do run `aggregateJacocoReports` before `coveralls`. Wonder if tasks dependencies are not working as they should.

https://github.com/jsr377/jsr377-converters

**Comment by aalmiray** [comment]
ping @musketyr. Is this still an issue?

**Comment by musketyr** [comment]
I still had to declare it explicitly

https://github.com/agorapulse/dru/blob/master/build.gradle#L119


út 26. 1. 2021 v 17:44 odesílatel Andres Almiray <notifications@github.com>
napsal:

**Comment by aalmiray** [comment]
I see. So the workaround makes it work but it'd be better if it worked out of the box without extra configuration, right?

**Comment by musketyr** [comment]
Yes. or at least explicitly documented.

**Comment by aalmiray** [comment]
I've tested with both single and multi-project builds that have at least 1 project with tests. As far as I can tell the `coveralls` plugins is set as enabled when the project contains Java sources. However applying the configuration to the `kordamp-gradle-plugins` build itself results in coveralls being disabled. Will keep looking.

**Comment by aalmiray** [comment]
Scratch that, it's not the fact that the project may contain Groovy code or not, it's if the rot project has tests or not.
I believe I have found the cause of problem.
