### ISSUE TITLE
[licensing] aggregateLicenseReport produces empty report by default

### ISSUE THREAD

**Issue by dmurat** [kordamp/kordamp-gradle-plugins#420]
When using the `aggregateLicenseReport` task, the generated report is empty. The problem stems from `com.hierynomus.gradle.license.LicenseReportingPlugin` that defines `"runtime"` as a default dependency configuration. As the "runtime" configuration is deprecated and does not contain any dependency, the report ends up empty.

The workaround is to explicitly configure `DownloadLicensesExtension` to use, say "runtimeClasspath" configuration:
```
downloadLicenses {
    dependencyConfiguration = "runtimeClasspath"
}
```

It would be great if kordamp can configure `LicenseReportingPlugin` or `DownloadLicensesExtension` to use "runtimeClasspath" as a default configuration. The report should then work out-of-the-box without any further configuration.

Tnx.

**Comment by aalmiray** [comment]
Thank you for the suggestion on how to fix this issue 😄
