### ISSUE TITLE
Adding tasks only if they don't exist yet

### ISSUE THREAD

**Issue by musketyr** [kordamp/kordamp-gradle-plugins#431]
For example both [SourceJarPlugin](https://github.com/kordamp/kordamp-gradle-plugins/blob/master/plugins/source-gradle-plugin/src/main/groovy/org/kordamp/gradle/plugin/source/SourceJarPlugin.groovy) and [GrailsPluginGradlePlugin](https://github.com/grails/grails-core/blob/master/grails-gradle-plugin/src/main/groovy/org/grails/gradle/plugin/core/GrailsPluginGradlePlugin.groovy) both creates `sourceJar` tasks. If `GrailsPluginGradlePlugin` is applied in a child project then the build fails to evaluate. Would be nice if the tasks are added only if the task is not already present. Other option would be not to add the tasks when it is disabled as this information should be known at the time of adding.

**Comment by aalmiray** [comment]
This may be a tricky thing to fix given that Gradle does not offer a proper way to handle multiple plugins contributing tasks that may override one another. We have access to `TaskContainer.register()` and `TaskContainer.matching()` which are lazy. `TaskContainer.findByName()` is eager.

What we need is a way to register a task if it does not exist yet, either at the point of checking or at the time the task graph is about to be resolved. Sadly there's no way to make it happen, cleanly.

**Comment by musketyr** [comment]
Ok, so what about the other option? Do not add the task when it is disabled?

**Comment by aalmiray** [comment]
Yes, that could work. As a matter of fact that was the original behavior many releases ago but then some tasks would fail as they could not find their requirements/dependencies, such as `createGuide` when an aggregate task was unavailable. I deiced then to still register tasks but disable them by default.

What about this, keep the current behavior but add a new flag that controls whether disabled tasks really get added or not. That way you have 3 options at hand:
- always register
- register but disable
- never register

**Comment by musketyr** [comment]
Sounds good!

**Comment by aalmiray** [comment]
I've decided to not add yet anther flag and go back to the previous behavior of skipping task registration in the plugin is disabled. It will work in the following way:

- aggregate tasks will always be registered but disabled by default.
- individual tasks will not be registered if they are unique to the plugin (i.e, `sourcesJar`)
- individual tasks will be disabled if they are not unique to the plugin (i.e, `mainCodenarc` because this task will always be registered by a 3rd party plugin).
