### ISSUE TITLE
Find an alternative to publish artifacts to Maven Central

### ISSUE THREAD

**Issue by aalmiray** [kordamp/kordamp-gradle-plugins#448]
See #447

**Comment by musketyr** [comment]
I believe this is the way https://github.com/gradle-nexus/publish-plugin (as @melix is using it in his own projects 🎖️ )

**Comment by aalmiray** [comment]
I spoke with Marcin and yes, this is the way to go. I still have to figure out multi-project releases though.

**Comment by musketyr** [comment]
cool. so I will just create my next OSS lib using the latest Kordamp and upgrade it once you figure this out 😺

**Comment by musketyr** [comment]
here are some examples of repositories using version `0.45.0` and publishing to the Maven Central

https://github.com/agorapulse/micronaut-worker
https://github.com/agorapulse/micronaut-aws-sdk

**Comment by aalmiray** [comment]
Thanks. I ended up using the profiles plugin to setup the GNPP as it messes up with local publication. GNPP always rewrites publishing URLs thus it's no longer possible to publish locally and check files unless the plugin is not applied.

https://github.com/kordamp/kordamp-parent/blob/master/plugins/kordamp-parentpom/src/main/groovy/org/kordamp/gradle/KordampParentPomPlugin.groovy

**Comment by musketyr** [comment]
But will you be able to close the staging repository?

**Comment by musketyr** [comment]
I'm running `publishToMavenLocal` without any issue

**Comment by aalmiray** [comment]
Yes, closing the repository is not a problem.
`publishToMavenLocal` is not an issue, it's invoking the `publish` task to write artifacts to the `localReleases` or `localSnapshots` directory the one that fails because GNPP is too broad in its configuration.

**Comment by aalmiray** [comment]
The `kordamp-parentpom` provides the behavior needed for this build.
The GNPP plugin provides behavior for any Gradle build.
