### ISSUE TITLE
[Guide] add .asciicdoctorconfig files by createGuide task

### ISSUE THREAD

**Issue by musketyr** [kordamp/kordamp-gradle-plugins#471]
this will enable out-of-the-box preview of snippets in IntelliJ

there should be one at the root of the project:

```
:root-dir: {asciidoctorconfigdir}
```

and another on in `src/docs/asciidoc`

```
:includedir: {asciidoctorconfigdir}
```

**Comment by aalmiray** [comment]
Do you have an example at a repository I can have a look?

**Comment by musketyr** [comment]
Here you go

**Comment by aalmiray** [comment]
I'm afraid I don't see the connection. Perhaps a PR would work best?

**Comment by musketyr** [comment]
see #475 ;-)
