### ISSUE TITLE
[Settings] Per-directory project prefix

### ISSUE THREAD

**Issue by musketyr** [kordamp/kordamp-gradle-plugins#484]
Hi,

we are having legacy multiprojects with nearly Kordamp layout - the only difference is that the projects in the directories are prefixed according the directory.

For example, projects inside `apps` directory are prefixed with `app-`. There are other logic relying on these naming conventions. It would help us a lot with the migration if we can specify the prefix in the `settings.gradle` file instead of renaming the directories.

Suggested implementation

```groovy
projects {
    prefixes = [apps: 'app-', libs: 'lib-', services: 'service-']
}
```

Or even simper collapsing the definition into one method call with the directory definition

```groovy
projects {
    directories 'docs', apps: 'app-', libs: 'lib-', services: 'service-'
}
```

**Comment by aalmiray** [comment]
Unfortunately you can't mix `List` and `Map` arguments in the same method.
Alternatively, your first suggestion could be used albeit hanging the proposed name to `directories`.

**Comment by musketyr** [comment]
ok, in that case I would be happy with the first solution with new `prefixes` property (and method if possible) accepting `Map<String, String>`.
