### ISSUE TITLE
Problem with pmd

### ISSUE THREAD

**Issue by tijanssen** [kordamp/kordamp-gradle-plugins#491]
I get the following error:

A problem occurred configuring project ':tresty-collections'.
> Could not set unknown property 'rulePriority' for task ':tresty-collections:allPmd' of type org.gradle.api.plugins.quality.Pmd.

I have added the org.kordamp.gradle.pmd plugin and have the pmd.xml in the config/pmd/ directory.
I have no congig qulity pmd block in the build.gradle.kts file. I was just trying to add the plugin without configuring it for my needs. 
DId I do something wrong?

**Comment by aalmiray** [comment]
@tijanssen the `org.kordamp.gradle.pmd` plugin is applied recursively to all plugins and becomes active by default if the given configuration is found at the right location, in other words, you don't have to use the DSL to activated it, this is why you're seeing it run.

It may be the case that a recent version of PMD no longer supports the `rulePriority` field, I'll have to check of this is true.

**Comment by tijanssen** [comment]
I tried it without setting the toolversion. In this case I get still the same error. I get the error even if I set enabled = false. I have to remove the org.kordamp.gradle.pmd plugin completely before i can continue to build my projects.
So I can't currently use the kordamp pmd plugin.

**Comment by tijanssen** [comment]
gradle 7.2 java 16
