### ISSUE TITLE
[Licensing] excludedSourceSets can't be set

### ISSUE THREAD

**Issue by choweiyuan** [kordamp/kordamp-gradle-plugins#502]
```
config {
  licensing {
   excludedSourceSets = ["**test**"]
    licenses {
      license {
        id = 'Apache-2.0'
      }
    }
  }
}

```
I have a simple config above and got the following error:
* What went wrong:
A problem occurred evaluating root project 'dashboard'.
> Cannot set the property 'excludedSourceSets' because the backing field is final.

Using Gradle 7.2

**Comment by choweiyuan** [comment]
0.47.0

**Comment by aalmiray** [comment]
You can invoke the `excludeSourceSet()` method

https://github.com/kordamp/kordamp-gradle-plugins/blob/e744cb7197e8ae0d9cc66c4b064f50776f08723d/plugins/base-gradle-plugin/src/main/groovy/org/kordamp/gradle/plugin/base/plugins/Licensing.groovy#L95-L99

or add to the property directly such as

```
config {
  licensing {
    excludedSourceSets.addAll(["**test**"])
    licenses {
      license {
        id = 'Apache-2.0'
      }
    }
  }
}
```

**Comment by choweiyuan** [comment]
I used the following and it worked, thank you!
`    
excludedSourceSets.addAll(["**test**"])
`
