### ISSUE TITLE
NPE with `java-platform` with 0.47.0 and Gradle 7.4.2

### ISSUE THREAD

**Issue by musketyr** [kordamp/kordamp-gradle-plugins#504]
Hi,

I'm trying to add `java-platform` subproject to the project using Kordamp `0.47.0` but I'm getting NPE from `withPom` configuration.

```
at org.kordamp.gradle.plugin.publishing.PublishingPlugin$_updatePublications_closure5$_closure6$_closure9$_closure10.doCall(PublishingPlugin.groovy:212)
```

Here's the full scan: https://scans.gradle.com/s/743zw4kv67ako/failure?expanded-stacktrace=WyIwLTEtMi0zIiwiMC0xLTIiLCIwLTEiLCIwIl0#1
Here's the PR with the project changed https://github.com/agorapulse/micronaut-worker/pull/19

I will be happy if you have any idea how to workaround it from within the subproject's Gradle script if there are no plans for releasing new version.

**Comment by musketyr** [comment]
I just wanted to report this bug to found that I already reported it 😅 

It still persists in `0.51.0`.

**Comment by aalmiray** [comment]
Bummer. I thought we had fixed it 😢
