### ISSUE TITLE
JacocoMerge has been removed in Gradle 8

### ISSUE THREAD

**Issue by vivekkothari** [kordamp/kordamp-gradle-plugins#517]
https://docs.gradle.org/current/userguide/upgrading_version_7.html

[JacocoMerge Task Removed](https://docs.gradle.org/current/userguide/upgrading_version_7.html#jacocomerge_task_removed)
The deprecated JacocoMerge task type has been removed. The same functionality is also available on the JacocoReport task.

Can we pls update this plugin to be compatible with gradle 8?

**Comment by aalmiray** [comment]
Completed with https://github.com/kordamp/kordamp-gradle-plugins/commit/db14cc04a6e109ec0bcc5d7bf182cbec6a5aa992
